# Ultralytics 🚀 AGPL-3.0 License - https://ultralytics.com/license

blank_issues_enabled: true
contact_links:
  - name: 📄 YOLOv8 Documentation
    url: https://docs.ultralytics.com/models/yolov8
    about: Model overview, benchmarks, and usage examples for Ultralytics YOLOv8
  - name: 🐛 Ultralytics Package Issues
    url: https://github.com/ultralytics/ultralytics/issues
    about: Report bugs in the ultralytics Python package or yolo CLI
  - name: 💬 Forum
    url: https://community.ultralytics.com/
    about: Ask on Ultralytics Community Forum
  - name: 🎧 Discord
    url: https://ultralytics.com/discord
    about: Ask on Ultralytics Discord
  - name: ⌨️ Reddit
    url: https://reddit.com/r/ultralytics
    about: Ask on Ultralytics Subreddit
